version: '3'

services:
  whos-playing-db:
    image: whos-playing-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: whosplaying
    ports:
      - "5432:5432"
    volumes:
      - ./core/dump.sql:/docker-entrypoint-initdb.d/dump.sql